### ISSUE TITLE
Remove keyword "EXPORTING" from automatic generation of a method body/signature

### ISSUE THREAD

**Issue by estevao-schultz-neto-SAP** [abapGit/ADT_Frontend#222]
Following the Clean ABAP rules widely adopted, it would be great if you could suppress the keyword: "EXPORTING" from the auto-completion method template.

For more information, please refer to:
https://github.com/SAP/code-pal-for-abap/blob/master/docs/checks/omit-optional-exporting.md

Yours,
Estevao Schultz-Neto
SAP SE

**Comment by larshp** [comment]
I dont think the abapGit ADT client has any control of method templates in ADT?

**Comment by estevao-schultz-neto-SAP** [comment]
> I dont think the abapGit ADT client has any control of method templates in ADT?

There were some folks willing to implement that in a plug-in. But I will put this issue on hold and adress it direclty to the ABAP Core folks.

**Comment by larshp** [comment]
yea, but again, its unrelated to abapGit?

**Comment by abinbaby-sap** [comment]
Hi Estevao,

As Lars already mentioned, this repository is only about the abapGit plugin in ADT. And the mentioned issue seems to be on general ADT behaviour on code completion. 

So, If the problem is not already resolved, you could probably reach out to the code completion colleagues in ADT via a ticket on component **BC-DWB-AIE-SRC**. Hope they would be able to help you out!!

Cheers Abin
